/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as GarantiaRouteImport } from './routes/garantia'
import { Route as FinanciamentoRouteImport } from './routes/financiamento'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelosIndexRouteImport } from './routes/modelos.index'
import { Route as ModelosYamahaRouteImport } from './routes/modelos.yamaha'
import { Route as ModelosSuduRouteImport } from './routes/modelos.sudu'
import { Route as ModelosSlugRouteImport } from './routes/modelos.$slug'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInstagramRouteImport } from './routes/_authenticated/instagram'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicModelImagesSplatRouteImport } from './routes/api/public/model-images/$'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiaRoute = GarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentoRoute = FinanciamentoRouteImport.update({
  id: '/financiamento',
  path: '/financiamento',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosIndexRoute = ModelosIndexRouteImport.update({
  id: '/modelos/',
  path: '/modelos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosYamahaRoute = ModelosYamahaRouteImport.update({
  id: '/modelos/yamaha',
  path: '/modelos/yamaha',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosSuduRoute = ModelosSuduRouteImport.update({
  id: '/modelos/sudu',
  path: '/modelos/sudu',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosSlugRoute = ModelosSlugRouteImport.update({
  id: '/modelos/$slug',
  path: '/modelos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstagramRoute = AuthenticatedInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicModelImagesSplatRoute =
  ApiPublicModelImagesSplatRouteImport.update({
    id: '/api/public/model-images/$',
    path: '/api/public/model-images/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/financiamento': typeof FinanciamentoRoute
  '/garantia': typeof GarantiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/modelos/sudu': typeof ModelosSuduRoute
  '/modelos/yamaha': typeof ModelosYamahaRoute
  '/modelos/': typeof ModelosIndexRoute
  '/api/public/model-images/$': typeof ApiPublicModelImagesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/financiamento': typeof FinanciamentoRoute
  '/garantia': typeof GarantiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/modelos/sudu': typeof ModelosSuduRoute
  '/modelos/yamaha': typeof ModelosYamahaRoute
  '/modelos': typeof ModelosIndexRoute
  '/api/public/model-images/$': typeof ApiPublicModelImagesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/financiamento': typeof FinanciamentoRoute
  '/garantia': typeof GarantiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/instagram': typeof AuthenticatedInstagramRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/modelos/sudu': typeof ModelosSuduRoute
  '/modelos/yamaha': typeof ModelosYamahaRoute
  '/modelos/': typeof ModelosIndexRoute
  '/api/public/model-images/$': typeof ApiPublicModelImagesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comparar'
    | '/contato'
    | '/faq'
    | '/financiamento'
    | '/garantia'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/analytics'
    | '/instagram'
    | '/leads'
    | '/whatsapp'
    | '/modelos/$slug'
    | '/modelos/sudu'
    | '/modelos/yamaha'
    | '/modelos/'
    | '/api/public/model-images/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comparar'
    | '/contato'
    | '/faq'
    | '/financiamento'
    | '/garantia'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/analytics'
    | '/instagram'
    | '/leads'
    | '/whatsapp'
    | '/modelos/$slug'
    | '/modelos/sudu'
    | '/modelos/yamaha'
    | '/modelos'
    | '/api/public/model-images/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comparar'
    | '/contato'
    | '/faq'
    | '/financiamento'
    | '/garantia'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/instagram'
    | '/_authenticated/leads'
    | '/_authenticated/whatsapp'
    | '/modelos/$slug'
    | '/modelos/sudu'
    | '/modelos/yamaha'
    | '/modelos/'
    | '/api/public/model-images/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompararRoute: typeof CompararRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  FinanciamentoRoute: typeof FinanciamentoRoute
  GarantiaRoute: typeof GarantiaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ModelosSlugRoute: typeof ModelosSlugRoute
  ModelosSuduRoute: typeof ModelosSuduRoute
  ModelosYamahaRoute: typeof ModelosYamahaRoute
  ModelosIndexRoute: typeof ModelosIndexRoute
  ApiPublicModelImagesSplatRoute: typeof ApiPublicModelImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantia': {
      id: '/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof GarantiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamento': {
      id: '/financiamento'
      path: '/financiamento'
      fullPath: '/financiamento'
      preLoaderRoute: typeof FinanciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/': {
      id: '/modelos/'
      path: '/modelos'
      fullPath: '/modelos/'
      preLoaderRoute: typeof ModelosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/yamaha': {
      id: '/modelos/yamaha'
      path: '/modelos/yamaha'
      fullPath: '/modelos/yamaha'
      preLoaderRoute: typeof ModelosYamahaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/sudu': {
      id: '/modelos/sudu'
      path: '/modelos/sudu'
      fullPath: '/modelos/sudu'
      preLoaderRoute: typeof ModelosSuduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/$slug': {
      id: '/modelos/$slug'
      path: '/modelos/$slug'
      fullPath: '/modelos/$slug'
      preLoaderRoute: typeof ModelosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram': {
      id: '/_authenticated/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AuthenticatedInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/model-images/$': {
      id: '/api/public/model-images/$'
      path: '/api/public/model-images/$'
      fullPath: '/api/public/model-images/$'
      preLoaderRoute: typeof ApiPublicModelImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedInstagramRoute: typeof AuthenticatedInstagramRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedInstagramRoute: AuthenticatedInstagramRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompararRoute: CompararRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  FinanciamentoRoute: FinanciamentoRoute,
  GarantiaRoute: GarantiaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ModelosSlugRoute: ModelosSlugRoute,
  ModelosSuduRoute: ModelosSuduRoute,
  ModelosYamahaRoute: ModelosYamahaRoute,
  ModelosIndexRoute: ModelosIndexRoute,
  ApiPublicModelImagesSplatRoute: ApiPublicModelImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
