/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelosIndexRouteImport } from './routes/modelos.index'
import { Route as ModelosSlugRouteImport } from './routes/modelos.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosIndexRoute = ModelosIndexRouteImport.update({
  id: '/modelos/',
  path: '/modelos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosSlugRoute = ModelosSlugRouteImport.update({
  id: '/modelos/$slug',
  path: '/modelos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/modelos/': typeof ModelosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/modelos': typeof ModelosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modelos/$slug': typeof ModelosSlugRoute
  '/modelos/': typeof ModelosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/modelos/$slug' | '/modelos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/modelos/$slug' | '/modelos'
  id: '__root__' | '/' | '/sitemap.xml' | '/modelos/$slug' | '/modelos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ModelosSlugRoute: typeof ModelosSlugRoute
  ModelosIndexRoute: typeof ModelosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/': {
      id: '/modelos/'
      path: '/modelos'
      fullPath: '/modelos/'
      preLoaderRoute: typeof ModelosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos/$slug': {
      id: '/modelos/$slug'
      path: '/modelos/$slug'
      fullPath: '/modelos/$slug'
      preLoaderRoute: typeof ModelosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ModelosSlugRoute: ModelosSlugRoute,
  ModelosIndexRoute: ModelosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
